[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"

[project]
name = "nse"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3",
    "duckdb>=1.4.3",
    "httpx",
    "pandera[polars]",
    "polars",
    "python-dotenv",
    "requests",
    "s3fs",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
]

[project.scripts]
nse = "nse.main:main"

