CREATE TABLE pd (
    MKT VARCHAR(2),
    SERIES VARCHAR(2),
    SYMBOL VARCHAR(20),
    SECURITY VARCHAR(20),
    PREV_CL_PR VARCHAR(20),
    OPEN_PRICE VARCHAR(20),
    HIGH_PRICE VARCHAR(20),
    LOW_PRICE VARCHAR(20),
    CLOSE_PRICE VARCHAR(20),
    NET_TRDVAL VARCHAR(20),
    NET_TRDQTY VARCHAR(20),
    IND_SEC VARCHAR(2),
    CORP_IND VARCHAR(2),
    TRADES VARCHAR(20),
    HI_52_WK VARCHAR(20),
    LO_52_WK VARCHAR(20)
);