CREATE TABLE sec (
    SYMBOL VARCHAR(20),
    SERIES VARCHAR(4),
    'DATE' DATE,
    PREV_CLOSE FLOAT,
    OPEN_PRICE FLOAT,
    HIGH_PRICE FLOAT,
    LOW_PRICE FLOAT,
    LAST_PRICE FLOAT,
    CLOSE_PRICE FLOAT,
    AVG_PRICE FLOAT,
    TTL_TRD_QNTY FLOAT,
    TURNOVER_LACS FLOAT,
    NO_OF_TRADES FLOAT,
    DELIV_QTY FLOAT,
    DELIV_PER FLOAT
    
);